name: greenwheel_user_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sizer2: ^2.0.16
  awesome_dialog: ^3.1.0
  transparent_image: ^2.0.1
  carousel_slider: ^4.2.1
  location: ^5.0.3
  dio: ^5.3.3
  input_quantity: ^2.1.1
  syncfusion_flutter_datepicker: ^23.1.42
  graphql_flutter: ^5.1.2
  http: ^0.13.6
  readmore: ^2.2.0
  collection: ^1.17.2
  mapbox_gl: ^0.16.0
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  shared_preferences: ^2.1.2
  pinput: ^3.0.1
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.9
  jwt_decode: ^0.3.1
  shimmer: ^3.0.0
  vnpay_client: ^0.0.3
  intl: ^0.18.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  uni_links: ^0.5.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  firebase_messaging: ^14.7.6
  flutter_barcode_scanner: ^2.0.0
  dart_jsonwebtoken: ^2.12.1
  flutter_local_notifications: ^16.2.0
  cupertino_icons: ^1.0.6
  uuid: ^3.0.7
  table_calendar: ^3.0.9
  internet_connection_checker: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  choose_input_chips: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-LightItalic.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
        - asset: assets/fonts/NotoSans-Thin.ttf
        - asset: assets/fonts/NotoSans-ThinItalic.ttf
