const String backIcon = "assets/images/back_arrow.png";
const String upIcon = "assets/images/up.png";
const String downIcon = "assets/images/down.png";
const String cartEmptyIcon = "assets/images/cart-empty.png";

const List<String> northSide = [
  "Hà Nội",
  "Quảng Ninh",
  "Vĩnh Phúc",
  "Bắc Ninh",
  "Hải Dương",
  "Hải Phòng",
  "Hưng Yên",
  "Thái Bình",
  "Hà Nam",
  "Nam Định",
  "Ninh Bình",
  "Hà Giang",
  "Cao Bằng",
  "Lào Cai",
  "Bắc Kạn",
  "Lạng Sơn",
  "Tuyên Quang",
  "Yên Bái",
  "Thái Nguyên",
  "Phú Thọ",
  "Bắc Giang",
  "Lai Châu",
  "Điện Biên",
  "Sơn La",
  "Hòa Bình",
];

const List<String> midSide = [
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Huế",
  "Đà Nẵng",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Khánh Hòa",
  "Ninh Thuận",
  "Bình Thuận",
  "Kon Tum",
  "Gia Lai",
  "Đắk Lắk",
  "Đắk Nông",
  "Lâm Đồng",
];

const List<String> southSide = [
  "Bình Phước",
  "Bình Dương",
  "Đồng Nai",
  "Tây Ninh",
  "Vũng Tàu",
  "Hồ Chí Minh",
  "Long An",
  "Đồng Tháp",
  "Tiền Giang",
  "An Giang",
  "Bến Tre",
  "Vĩnh Long",
  "Trà Vinh",
  "Hậu Giang",
  "Kiên Giang",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
];
