import 'package:flutter/material.dart';
import 'package:greenwheel_user_app/models/tag.dart';

List<Tag> searchTags = [
  Tag(
      id: "1",
      title: "Hồ",
      type: "topographic",
      enumName: "LAKE",
      mainColor: Colors.white,
      strokeColor: Color(0xFF59CDFF)),
  Tag(
      id: "2",
      title: "Núi",
      type: "topographic",
      enumName: "MOUNTAIN",
      mainColor: Colors.white,
      strokeColor: Color(0xFFE79901)),
  Tag(
      id: "3",
      title: "Biển",
      type: "topographic",
      enumName: "BEACH",
      mainColor: Colors.white,
      strokeColor: Color(0xFF006590)),
  Tag(
      id: "4",
      title: "Suối",
      type: "topographic",
      enumName: "BROOK",
      mainColor: Colors.white,
      strokeColor: Color(0xFF5869FF)),
  Tag(
      id: "5",
      title: "Rừng",
      type: "topographic",
      enumName: "JUNGLE",
      mainColor: Colors.white,
      strokeColor: Color(0xFF007613)),
  Tag(
      id: "6",
      title: "Hang động",
      type: "topographic",
      enumName: "CAVE",
      mainColor: Colors.white,
      strokeColor: Color(0xFF5C645E)),
  Tag(
      id: "7",
      title: "Đồi cát",
      type: "topographic",
      enumName: "DUNE",
      mainColor: Colors.white,
      strokeColor: Color(0xFFFFE500)),
  Tag(
      id: "8",
      title: "Thác",
      type: "topographic",
      enumName: "WATERFALL",
      mainColor: Colors.white,
      strokeColor: Color(0xFF31FFE6)),
  Tag(
      id: "9",
      title: "Tắm",
      type: "activities",
      enumName: "BATHING",
      mainColor: Color(0xFF59CDFF),
      strokeColor: Colors.black),
  Tag(
      id: "10",
      title: "Cắm trại",
      type: "activities",
      enumName: "CAMPING",
      mainColor: Color(0xFF82E0AA),
      strokeColor: Colors.black),
  Tag(
      id: "11",
      title: "Leo trèo",
      type: "activities",
      enumName: "CLIMBING",
      mainColor: Color(0xFFE79901),
      strokeColor: Colors.black),
  Tag(
      id: "12",
      title: "Chèo thuyền",
      type: "activities",
      enumName: "PADDLING",
      mainColor: Color(0xFF01E7BD),
      strokeColor: Colors.black),
  Tag(
      id: "13",
      title: "Lặn",
      type: "activities",
      enumName: "DIVING",
      mainColor: Color(0xFF96A1FF),
      strokeColor: Colors.black),
  Tag(
      id: "14",
      title: "Lướt sóng",
      type: "activities",
      enumName: "SURFING",
      mainColor: Color(0xFFA5FFEF),
      strokeColor: Colors.black),
  Tag(
      id: "15",
      title: "Câu cá",
      type: "activities",
      enumName: "FISHING",
      mainColor: Color(0xFF49B9F9),
      strokeColor: Colors.black),
  Tag(
    id: "16",
    title: "Xuân",
    type: "seasons",
    enumName: "SPRING",
    mainColor: Color(0xFF82E0AA),
  ),
  Tag(
    id: "17",
    title: "Hạ",
    type: "seasons",
    enumName: "SUMMER",
    mainColor: Color(0xFFFFB967),
  ),
  Tag(
    id: "18",
    title: "Thu",
    type: "seasons",
    enumName: "FALL",
    mainColor: Color(0xFFF0D984),
  ),
  Tag(
    id: "19",
    title: "Đông",
    type: "seasons",
    enumName: "PADDLING",
    mainColor: Color(0xFF33D8D8),
  ),
];
