import 'package:greenwheel_user_app/view_models/plan_viewmodels/combo_date.dart';


    List<ComboDate> listComboDate = const [
      ComboDate(id: 1, numberOfDay: 1, numberOfNight: 1, duration: 2),
      ComboDate(id: 2, numberOfDay: 2, numberOfNight: 1, duration: 3),
      ComboDate(id: 3, numberOfDay: 2, numberOfNight: 2, duration: 4),
      ComboDate(id: 4, numberOfDay: 3, numberOfNight: 2, duration: 5),
      ComboDate(id: 5, numberOfDay: 3, numberOfNight: 3, duration: 6),
      ComboDate(id: 6, numberOfDay: 4, numberOfNight: 3, duration: 7),
      ComboDate(id: 7, numberOfDay: 4, numberOfNight: 4, duration: 8),
      ComboDate(id: 8, numberOfDay: 5, numberOfNight: 4, duration: 9),
      ComboDate(id: 9, numberOfDay: 5, numberOfNight: 5, duration: 10),
      ComboDate(id: 10, numberOfDay: 6, numberOfNight: 5, duration: 11),
      ComboDate(id: 11, numberOfDay: 6, numberOfNight: 6, duration: 12),
      ComboDate(id: 12, numberOfDay: 7, numberOfNight: 6, duration: 13),
      ComboDate(id: 13, numberOfDay: 7, numberOfNight: 7, duration: 14),
      ComboDate(id: 14, numberOfDay: 8, numberOfNight: 7, duration: 15),
      ComboDate(id: 15, numberOfDay: 8, numberOfNight: 8, duration: 16),
      ComboDate(id: 16, numberOfDay: 9, numberOfNight: 8, duration: 17),
      ComboDate(id: 17, numberOfDay: 9, numberOfNight: 9, duration: 18),
      ComboDate(id: 18, numberOfDay: 10, numberOfNight: 9, duration: 19),
      ComboDate(id: 19, numberOfDay: 10, numberOfNight: 10, duration: 20),
      ComboDate(id: 20, numberOfDay: 11, numberOfNight: 10, duration: 21),
      ComboDate(id: 21, numberOfDay: 11, numberOfNight: 11, duration: 22),
      ComboDate(id: 22, numberOfDay: 12, numberOfNight: 11, duration: 23),
      ComboDate(id: 23, numberOfDay: 12, numberOfNight: 12, duration: 24),
      ComboDate(id: 24, numberOfDay: 13, numberOfNight: 12, duration: 25),
      ComboDate(id: 25, numberOfDay: 13, numberOfNight: 13, duration: 26),
      ComboDate(id: 26, numberOfDay: 14, numberOfNight: 13, duration: 27),
      ComboDate(id: 27, numberOfDay: 14, numberOfNight: 14, duration: 28),
      // ComboDate(id: 28, numberOfDay: 15, numberOfNight: 14, duration: 29),
      // ComboDate(id: 29, numberOfDay: 15, numberOfNight: 15, duration: 30),
      // ComboDate(id: 30, numberOfDay: 16, numberOfNight: 15, duration: 31),
      // ComboDate(id: 31, numberOfDay: 16, numberOfNight: 16, duration: 32),
      // ComboDate(id: 32, numberOfDay: 17, numberOfNight: 16, duration: 33),
      // ComboDate(id: 33, numberOfDay: 17, numberOfNight: 17, duration: 34),
      // ComboDate(id: 34, numberOfDay: 18, numberOfNight: 17, duration: 35),
      // ComboDate(id: 35, numberOfDay: 18, numberOfNight: 18, duration: 36),
      // ComboDate(id: 36, numberOfDay: 19, numberOfNight: 18, duration: 37),
      // ComboDate(id: 37, numberOfDay: 19, numberOfNight: 19, duration: 38),
      // ComboDate(id: 38, numberOfDay: 20, numberOfNight: 19, duration: 39),
      // ComboDate(id: 39, numberOfDay: 20, numberOfNight: 20, duration: 40),
      // ComboDate(id: 40, numberOfDay: 21, numberOfNight: 20, duration: 41),
      // ComboDate(id: 41, numberOfDay: 21, numberOfNight: 21, duration: 42),
      // ComboDate(id: 42, numberOfDay: 22, numberOfNight: 21, duration: 43),
      // ComboDate(id: 43, numberOfDay: 22, numberOfNight: 22, duration: 44),
      // ComboDate(id: 44, numberOfDay: 23, numberOfNight: 22, duration: 45),
      // ComboDate(id: 45, numberOfDay: 23, numberOfNight: 23, duration: 46),
      // ComboDate(id: 46, numberOfDay: 24, numberOfNight: 23, duration: 47),
      // ComboDate(id: 47, numberOfDay: 24, numberOfNight: 24, duration: 48),
      // ComboDate(id: 48, numberOfDay: 25, numberOfNight: 24, duration: 49),
      // ComboDate(id: 49, numberOfDay: 25, numberOfNight: 25, duration: 50),
      // ComboDate(id: 50, numberOfDay: 26, numberOfNight: 25, duration: 51),
      // ComboDate(id: 51, numberOfDay: 26, numberOfNight: 26, duration: 52),
      // ComboDate(id: 52, numberOfDay: 27, numberOfNight: 26, duration: 53),
      // ComboDate(id: 53, numberOfDay: 27, numberOfNight: 27, duration: 54),
      // ComboDate(id: 54, numberOfDay: 28, numberOfNight: 27, duration: 55),
      // ComboDate(id: 55, numberOfDay: 28, numberOfNight: 28, duration: 56),
      // ComboDate(id: 56, numberOfDay: 29, numberOfNight: 28, duration: 57),
      // ComboDate(id: 57, numberOfDay: 29, numberOfNight: 29, duration: 58),
      // ComboDate(id: 58, numberOfDay: 30, numberOfNight: 29, duration: 59),
      // ComboDate(id: 59, numberOfDay: 30, numberOfNight: 30, duration: 60),
      // ComboDate(id: 60, numberOfDay: 31, numberOfNight: 30, duration: 61),
      // ComboDate(id: 61, numberOfDay: 31, numberOfNight: 31, duration: 62),
    ];
