import 'package:phuot_app/view_models/plan_viewmodels/combo_date.dart';


    List<ComboDate> listComboDate = const [
      ComboDate(id: 1, numberOfDay: 1, numberOfNight: 1, duration: 2),
      ComboDate(id: 2, numberOfDay: 2, numberOfNight: 1, duration: 3),
      ComboDate(id: 3, numberOfDay: 2, numberOfNight: 2, duration: 4),
      ComboDate(id: 4, numberOfDay: 3, numberOfNight: 2, duration: 5),
      ComboDate(id: 5, numberOfDay: 3, numberOfNight: 3, duration: 6),
      ComboDate(id: 6, numberOfDay: 4, numberOfNight: 3, duration: 7),
      ComboDate(id: 7, numberOfDay: 4, numberOfNight: 4, duration: 8),
      ComboDate(id: 8, numberOfDay: 5, numberOfNight: 4, duration: 9),
      ComboDate(id: 9, numberOfDay: 5, numberOfNight: 5, duration: 10),
      ComboDate(id: 10, numberOfDay: 6, numberOfNight: 5, duration: 11),
      ComboDate(id: 11, numberOfDay: 6, numberOfNight: 6, duration: 12),
      ComboDate(id: 12, numberOfDay: 7, numberOfNight: 6, duration: 13),
      ComboDate(id: 13, numberOfDay: 7, numberOfNight: 7, duration: 14),
      ComboDate(id: 14, numberOfDay: 8, numberOfNight: 7, duration: 15),
      ComboDate(id: 15, numberOfDay: 8, numberOfNight: 8, duration: 16),
      ComboDate(id: 16, numberOfDay: 9, numberOfNight: 8, duration: 17),
      ComboDate(id: 17, numberOfDay: 9, numberOfNight: 9, duration: 18),
      ComboDate(id: 18, numberOfDay: 10, numberOfNight: 9, duration: 19),
      ComboDate(id: 19, numberOfDay: 10, numberOfNight: 10, duration: 20),
      ComboDate(id: 20, numberOfDay: 11, numberOfNight: 10, duration: 21),
      ComboDate(id: 21, numberOfDay: 11, numberOfNight: 11, duration: 22),
      ComboDate(id: 22, numberOfDay: 12, numberOfNight: 11, duration: 23),
      ComboDate(id: 23, numberOfDay: 12, numberOfNight: 12, duration: 24),
      ComboDate(id: 24, numberOfDay: 13, numberOfNight: 12, duration: 25),
      ComboDate(id: 25, numberOfDay: 13, numberOfNight: 13, duration: 26),
      ComboDate(id: 26, numberOfDay: 14, numberOfNight: 13, duration: 27),
      ComboDate(id: 27, numberOfDay: 14, numberOfNight: 14, duration: 28),
      ComboDate(id: 28, numberOfDay: 15, numberOfNight: 14, duration: 29),
      ComboDate(id: 29, numberOfDay: 15, numberOfNight: 15, duration: 30),
    ];
